### ISSUE TITLE
Problems installing 

### ISSUE THREAD

**Issue by LukasMHD** [jakob-beetz/IfcOpenShellScriptingTutorial#1]
Hello Jakob,
I seem to have trouble trying to install your viewer. 
After a couple of tries i finally built the whole IFCOpenShell and all the dependencies, and now I want to integrate your viewer as well. 
But when i do what you instructed in the Scripting Tutorial, i get this error:

>   File "C:\Users\...\ifcopenshell\app\tue_viewer\lib\site-packages\ifcopenshell\geom\code_editor_pane.py", line 150, in __init__
>     self.snippets = config.options('snippets')
>   File "C:\Users\...\ifcopenshell\app\tue_viewer\lib\site-packages\ifcopenshell\geom\app.py", line 112, in options
>     return OrderedDict([(k, self.config_decode(self.config.get(s, k))) for k in self.config.options(s)])
>   File "C:\Users\...\ifcopenshell\app\tue_viewer\lib\ConfigParser.py", line 279, in options
>     raise NoSectionError(section)
> ConfigParser.NoSectionError: No section: 'snippets'

Any help, or a step by step how to integrate the viewer into the IfcOpenshell project would be greatly appreciated!
Kind regards,
Lukas.

**Comment by jakob-beetz** [comment]
Hi Lukas,

thank you for your interest and feedback! 
Could you check whether you have got a settings file https://github.com/jakob-beetz/IfcOpenShellScriptingTutorial/blob/master/src/snippets.conf  in the designated destination ({WINDOWS_USER}/.openshell/app/snippets.conf  ?
I looks like the issues is caused by this...
Hope this helps
Jakob

**Comment by LukasMHD** [comment]
Hey Jakob, 
thanks for your help, it works now ..  i did have the file, but it was in the wrong path .. (ifsopenshell/.. instead of .ifcopenshell/.. )
Lukas
