### ISSUE TITLE
Input problems

### ISSUE THREAD

**Issue by LukasMHD** [jakob-beetz/IfcOpenShellScriptingTutorial#2]
Hello,
this application is really great! And i liked your Tutorial as well.
I just noticed that my version of this app crashes whenever i try to run raw_input, or input,
do you know why this should be? 
Thanks in advance, 
best regards,
Lukas.

**Comment by aothms** [comment]
Hi,

I suppose that indeed the application would hang when invoking `raw_input()` from the Script Code Editor. Probably simply because stdin is not connected to something and the read call blocks processing the window events.

Luckily there are much better ways to ask for user input. PyQt comes with a bunch of convenience functions that wrap the creation of proper model dialogs.

For example:

~~~
from PyQt4 import QtGui
app = QtGui.QApplication.instance()
result, ok = QtGui.QInputDialog.getInt(app.window, "title", "number")
if ok:
    print result
~~~

Hope that helps,

Kind regards,
Thomas

**Comment by LukasMHD** [comment]
Thank you, that helped a lot!
